config/routes.rb
Sudu::Application.routes.draw do
  devise_scope :user do
    get :new_user_session, :path => 'login', :to => "devise/sessions#new"
    post :user_session, :path => 'login', :to => "devise/sessions#create"
    match :destroy_user_session, :path => 'logout', :to => "devise/sessions#destroy", :via => [ :post, :delete ]

    get :new_user_registration, :path => 'sign_up', :to => "users/registrations#new"
    post :reset_feed_token, :path => 'users/reset_feed_token', :to => "users/registrations#reset_feed_token"
  end
  devise_for :users, :skip => :sessions, :controllers => { :registrations => 'users/registrations' } 

  resources :projects, :only => [:index,:show,:edit,:update,:create,:destroy] do
    delete :leave
    get :role_new, :path => 'roles/new', :action => :new_role
    delete :role_destroy, :path => "roles/:id", :action => :destroy_role
    
    post :lists, :action => :create_list
  end

  resources :todo_items, :path => :items, :only => [:show,:update,:destroy] do
    resources :todo_item_changes, :path => :changes, :only => [:show]
  end
  resources :todo_lists, :path => :lists, :only => [:show,:edit,:update,:destroy] do
    collection do
      post :create_item
    end
    get :item_new, :path => 'items/new', :action => :new_item
  end

  match :markdown, :controller => :markdown, :action => :index, :via => [ :get, :put, :post ]

  get :feed, :to => 'feed#index'

  devise_scope :admin do
    get :new_admin_session, :path => 'admin/login', :to => "devise/sessions#new"
    post :admin_session, :path => 'admin/login', :to => "devise/sessions#create"
    match :destroy_admin_session, :path => 'admin/logout', :to => "devise/sessions#destroy", :via => [ :post, :delete ]
  end
  devise_for :admins, :path => "admin/admins", :skip => :sessions

  namespace :admin do
    authenticated :admin do
      get :dashboard_index, :path => '/', :to => "dashboard#index"
    end

    resources :projects, :only => [:index,:create,:show,:update,:destroy] do
      get :role_new, :path => 'roles/new', :action => :new_role
      delete :role_destroy, :path => "roles/:id", :action => :destroy_role
    end
    resources :admins, :only => [:index,:create,:show,:update,:destroy]
    resources :users, :only => [:index,:create,:show,:update,:destroy] do
      member do
        post :become
        post :lock
        post :unlock
        post :restore
        post :confirm
        post :make_admin
      end
    end
  end

  authenticated :user do
    get :dashboard_index, :path => '/', :to => "dashboard#index"
  end

  devise_scope :user do
    root :to => "devise/sessions#new"
  end

  devise_scope :admin do
    get :admin_root, :path => 'admin', :to => "devise/sessions#new"
  end

end

app/views/layouts/admin/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sudu - Admin</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container-fluid">
	<div class="row-fluid">
		<div class="nav-head span10 offset1">
			<b>Sudu - Shared todo list manager</b>
			<div class="btn-group pull-right">
				<a class="btn btn-danger dropdown-toggle" data-toggle="dropdown" href="#">Session<span class="caret"></span></a>
				<ul class="dropdown-menu">
					<li><%= link_to (user_signed_in? ? "Dashboard" : "Sign in"), root_path %></li>
					<li><%= link_to (admin_signed_in? ? "Admin Dashboard" : "Admin Sign in"), admin_root_path %></li>
<% if user_signed_in? %>
					<li class="divider"></li>
					<li>
    					<%= link_to "Account", edit_user_registration_path %>
    					<%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
    				</li>
<% end %>
<% if admin_signed_in? %>
					<li class="divider"></li>
					<li>
    					<%= link_to "Admin Account", admin_admin_path(current_admin) %>
						<%= link_to "Admin Sign out", destroy_admin_session_path, :method => :delete %>
    				</li>
<% end %>
				</ul>
			</div>
		</div>
		<div class="span1">
		</div>
	</div>
	<div class="row-fluid">
		<% if admin_signed_in? %>
			<div class="span2 offset1">
				<div class="well well-small"><ul class="nav nav-list nav-admin">
					<%= menu_link "Dashboard", admin_dashboard_index_path, "nav-header" %>
					<li class="divider"></li>
					<%= menu_link "Administrators", admin_admins_path, "nav-header" %>
					<%= menu_link "Users", admin_users_path, "nav-header" %>
					<%= menu_link "Projects", admin_projects_path, "nav-header" %>
				</ul></div>
			</div>
			<div class="span8">
				<%= render "layouts/flash" %>
				
				<%= yield %>
			</div>
		<% else %>
			<div class="span6 offset3">
				<%= render "layouts/flash" %>
				
				<%= yield %>
			</div>
		<% end %>
	</div>
</body>
</html>