config/routes.rb
Sudu::Application.routes.draw do
  devise_scope :user do
    get :new_user_session, :path => 'login', :to => "devise/sessions#new"
    post :user_session, :path => 'login', :to => "devise/sessions#create"
    match :destroy_user_session, :path => 'logout', :to => "devise/sessions#destroy", :via => [ :post, :delete ]

    get :new_user_registration, :path => 'sign_up', :to => "users/registrations#new"
    post :reset_feed_token, :path => 'users/reset_feed_token', :to => "users/registrations#reset_feed_token"
  end
  devise_for :users, :skip => :sessions, :controllers => { :registrations => 'users/registrations' } 

  resources :projects, :only => [:index,:show,:edit,:update,:create,:destroy] do
    delete :leave
    get :role_new, :path => 'roles/new', :action => :new_role
    delete :role_destroy, :path => "roles/:id", :action => :destroy_role
    
    post :lists, :action => :create_list
  end

  resources :todo_items, :path => :items, :only => [:show,:update,:destroy] do
    resources :todo_item_changes, :path => :changes, :only => [:show]
  end
  resources :todo_lists, :path => :lists, :only => [:show,:edit,:update,:destroy] do
    collection do
      post :create_item
    end
    get :item_new, :path => 'items/new', :action => :new_item
  end

  match :markdown, :controller => :markdown, :action => :index, :via => [ :get, :put, :post ]

  get :feed, :to => 'feed#index'

  devise_scope :admin do
    get :new_admin_session, :path => 'admin/login', :to => "devise/sessions#new"
    post :admin_session, :path => 'admin/login', :to => "devise/sessions#create"
    match :destroy_admin_session, :path => 'admin/logout', :to => "devise/sessions#destroy", :via => [ :post, :delete ]
  end
  devise_for :admins, :path => "admin/admins", :skip => :sessions

  namespace :admin do
    authenticated :admin do
      get :dashboard_index, :path => '/', :to => "dashboard#index"
    end

    resources :projects, :only => [:index,:create,:show,:update,:destroy] do
      get :role_new, :path => 'roles/new', :action => :new_role
      delete :role_destroy, :path => "roles/:id", :action => :destroy_role
    end
    resources :admins, :only => [:index,:create,:show,:update,:destroy]
    resources :users, :only => [:index,:create,:show,:update,:destroy] do
      member do
        post :become
        post :lock
        post :unlock
        post :restore
        post :confirm
        post :make_admin
      end
    end
  end

  authenticated :user do
    get :dashboard_index, :path => '/', :to => "dashboard#index"
  end

  devise_scope :user do
    root :to => "devise/sessions#new"
  end

  devise_scope :admin do
    get :admin_root, :path => 'admin', :to => "devise/sessions#new"
  end

end

app/models/project.rb
class Project < ActiveRecord::Base
  attr_accessible :name

  has_many :roles, :class_name => "ProjectRole", :dependent => :destroy
  has_many :users, :through => :roles, :uniq => true
  
  has_many :lists, :class_name => "TodoList", :dependent => :destroy
  has_many :items, :through => :lists
  
  validates_presence_of :name
  
  def last_managing_role
    managing_roles.count == 1
  end
  
  def managing_roles
    roles.where(["abilities LIKE :a", {:a => '%:manage:%'}])
  end
  
  def last_managing_user
    managing_users.count == 1
  end
  
  def managing_users
    User.joins(:project_roles).where(["project_roles.abilities LIKE ? AND project_roles.project_id = ?", '%:manage:%', id]).uniq
  end  
end

app/controllers/admin/projects_controller.rb
class Admin::ProjectsController < Admin::AdminController
  def index
    @projects = Project

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @projects.all }
    end
  end

  def show
    @project = Project.find(params[:id], :include => :roles)

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @project }
    end
  end

  def new_role
    @project = Project.find(params[:project_id], :include => :roles)
    @role = @project.roles.new(:name => "New Role")

    respond_to do |format|
      format.html { render :action => "show" }
      format.json { render json: @role }
    end
  end

  def destroy_role
    @project = Project.find(params[:project_id])
    @project.roles.find(params[:id]).destroy

    respond_to do |format|
      format.html { redirect_to admin_project_path(@project) }
      format.json { head :no_content }
    end
  end

  def create
    @project = Project.create(:name => params[:project][:name])

    respond_to do |format|
      if @project.valid? then
        format.html { redirect_to admin_project_path(@project), notice: 'Project was successfully created.' }
        format.json { render json: @project, status: :created, location: admin_project_path(@project) }
      else
        format.html { redirect_to admin_projects_path, alert: 'Project was not created, empty name not allowed' }
        format.json { render :json => { :errors => @project.errors }, :status => :unprocessable_entity}
      end
    end
  end

  def update
    @project = Project.find(params[:id])

    @project.transaction do
      @project.name = params[:project][:name]
      @project.save

      update_roles
    end

    respond_to do |format|
      if @project.errors.empty? then
        format.html { redirect_to admin_project_path(@project), notice: 'Project was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "show" }
        format.json { render :json => { :errors => @project.errors }, :status => :unprocessable_entity}
      end
    end
  end

  def destroy
    @project = Project.find(params[:id])
    @project.destroy

    respond_to do |format|
      format.html { redirect_to admin_projects_url }
      format.json { head :no_content }
    end
  end

private
  def update_roles
    p = params[:project]
    p[:roles] ||= {}
    p[:roles].each do |k,v|
      if k.to_i > 0
        role = @project.roles.find(k)
      else
        role = @project.roles.create(:name => v[:name])
      end
      next if role.nil?
      v[:name] ||= ''
      v[:was_ability] ||= {}
      v[:set_ability] ||= {}
      v[:had_member] ||= {}
      v[:still_member] ||= {}
      v[:new_member] ||= {}
      v[:new_members] ||= ''
      role[:name] = v[:name] unless v[:name].empty?
      role.save
      Ability::Project_Abilities.keys.each do |a|
        if v[:was_ability][a] != (v[:set_ability][a] || 'false')
          if v[:set_ability][a]
            role.add_ability!(a)
          else
            role.remove_ability!(a)
          end
        end
      end
      v[:had_member].keys.each do |userid|
        next if v[:still_member][userid]
        u = User.find(userid)
        if u.nil? or u.deleted_at
          @project.errors[:base] << "Userid #{userid} does not exist"
          next
        end
        role.users.delete(u) if role.users.include?(u)
      end
      v[:new_member].keys.each do |userid|
        u = User.find(userid)
        if u.nil? or u.deleted_at
          @project.errors[:base] << "Userid #{userid} does not exist"
          next
        end
        role.users << u unless role.users.include?(u)
      end
      v[:new_members].split('/ +/').each do |username|
        u = User.find_first_by_auth_conditions({ login: username })
        if u.nil? or u.deleted_at
          @project.errors[:base] << "User #{username} does not exist"
          next
        end
        role.users << u unless role.users.include?(u)
      end
    end
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
    @projects = current_user.projects

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @projects }
    end
  end

  def show
    @project = Project.find(params[:id], :include => :roles)
    authorize! :read, @project

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @project }
    end
  end

  def edit
    @project = Project.find(params[:id], :include => :roles)
    authorize! :manage, @project
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @project }
    end
  end

  def update
    @project = Project.find(params[:id])
    authorize! :manage, @project
    
    @project.transaction do
      @project.name = params[:project][:name]
      @project.save
  
      update_roles
      unless @project.managing_users.count > 0
        @project.errors[:base] << "No project administrator remaining"
      end
      raise ActiveRecord::Rollback unless @project.errors.empty?
    end

    respond_to do |format|
      if @project.errors.empty? then
        format.html { redirect_to edit_project_path(@project), notice: 'Project was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => { :errors => @project.errors }, :status => :unprocessable_entity}
      end
    end
  end

  # just extends edit form to show a new role
  def new_role
    @project = Project.find(params[:project_id], :include => :roles)
    authorize! :manage, @project
    @role = @project.roles.new(:name => "New Role")

    respond_to do |format|
      format.html { render :action => "edit" }
      format.json { render json: @role }
    end
  end

  def destroy_role
    @project = Project.find(params[:project_id])
    authorize! :manage, @project

    @project.transaction do
      @project.roles.find(params[:id]).destroy

      unless @project.managing_users.count > 0
        @project.errors[:base] << "No project administrator remaining"
      end
      raise ActiveRecord::Rollback unless @project.errors.empty?
    end

    respond_to do |format|
      if @project.errors.empty?
        format.html { redirect_to edit_project_path(@project) }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => { :errors => @project.errors }, :status => :unprocessable_entity}
      end
    end
  end

  def create_list
    @project = Project.find(params[:project_id])
    authorize! :manage_list, @project
    @list = @project.lists.create(:name => params[:new_list][:name])
    
    respond_to do |format|
      if @list.valid?
        format.html { redirect_to @list, notice: 'List was successfully created.' }
        format.json { render json: @list, status: :created, location: @list }
      else
        @project.reload
        format.html { redirect_to @project, alert: 'List was not created, empty name not allowed' }
        format.json { render :json => { :errors => @list.errors }, :status => :unprocessable_entity}
      end
    end
  end

  def create
    @project = Project.create(:name => params[:project][:name])
    @project.roles.create(:name => "Administrators", :abilities => [:manage], :users => [current_user]) if @project.valid?

    respond_to do |format|
      if @project.valid?
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render json: @project, status: :created, location: project_path(@project) }
      else
        format.html { redirect_to projects_path, alert: 'Project was not created, empty name not allowed' }
        format.json { render :json => { :errors => @project.errors }, :status => :unprocessable_entity}
      end
    end
  end

  def destroy
    @project = Project.find(params[:id])
    authorize! :manage, @project
    @project.destroy

    respond_to do |format|
      format.html { redirect_to projects_url }
      format.json { head :no_content }
    end
  end

  def leave
    @project = Project.find(params[:project_id])
    authorize! :read, @project
    wasadmin = can? :manage, @project

    success = @project.transaction do
      @project.last_managing_user
      @project.roles.each do |role|
        role.users.delete(current_user)
      end

      unless @project.managing_users.count > 0 or !wasadmin
        @project.errors[:base] << "No project administrator remaining"
      end
      raise ActiveRecord::Rollback unless @project.errors.empty?
    end

    respond_to do |format|
      if @project.errors.empty?
        format.html { redirect_to projects_url }
        format.json { head :no_content }
      else
        format.html { render :action => "show" }
        format.json { render :json => { :errors => @project.errors }, :status => :unprocessable_entity}
      end
    end
  end

private
  def update_roles
    p = params[:project]
    p[:roles] ||= {}
    p[:roles].each do |k,v|
      if k.to_i > 0
        role = @project.roles.find(k)
      else
        role = @project.roles.create(:name => v[:name])
      end
      next if role.nil?
      v[:name] ||= ''
      v[:was_ability] ||= {}
      v[:set_ability] ||= {}
      v[:had_member] ||= {}
      v[:still_member] ||= {}
      v[:new_member] ||= {}
      v[:new_members] ||= ''
      role[:name] = v[:name] unless v[:name].empty?
      role.save
      Ability::Project_Abilities.keys.each do |a|
        if v[:was_ability][a] != (v[:set_ability][a] || 'false')
          if v[:set_ability][a]
            role.add_ability!(a)
          else
            role.remove_ability!(a)
          end
        end
      end
      is_mrole = role.has_ability?(:manage)
      v[:had_member].keys.each do |userid|
        next if v[:still_member][userid]
        u = User.find(userid)
        if u.nil? or u.deleted_at
          @project.errors[:base] << "Userid #{userid} does not exist"
          next
        end
        next unless role.users.include?(u)
        role.users.delete(u)
      end
      v[:new_member].keys.each do |userid|
        u = User.find(userid)
        if u.nil? or u.deleted_at
          @project.errors[:base] << "Userid #{userid} does not exist"
          next
        end
        role.users << u unless role.users.include?(u)
      end
      v[:new_members].split('/ +/').each do |username|
        u = User.find_by_username(username)
        if u.nil? or u.deleted_at
          @project.errors[:base] << "Username #{username} does not exist"
          next
        end
        role.users << u unless role.users.include?(u)
      end
    end
  end
end

app/views/projects/_form.html.erb
<%= form_for(@project, :url => project_path(@project)) do |f| -%>
	<% if @project.errors.any? -%>
		<div id="error_explanation">
			<h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

			<ul>
				<% @project.errors.full_messages.each do |msg| -%>
					<li><%= msg %></li>
				<% end -%>
			</ul>
		</div>
	<% end -%>

	<div class="input-prepend">
		<%= f.label :name, class: 'btn' %>
		<%= f.text_field :name %>
	</div>

	<h2>Roles</h2>

	<ul>
		<% availAbilities = Ability::Project_Abilities.keys %>
		<% roleNewID = -1 %>
		<% @project.roles.each do |role| %>
			<% role_prefix = role.new_record? ? roleNewID : role.id %>
			<% roleNewID -= 1 if role.new_record? %>
				<li>
					<%= fields_for "project[roles][#{role_prefix}]", role do |fr| %>
						<div>
						<%= fr.text_field :name %>
						<% unless role.new_record? %>
							<%= link_to 'Delete role', project_role_destroy_path(@project, role), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
						<% end %>
						</div>

						<div style="display:inline-block;vertical-align:top;padding-right: 20px;">
							Permissions:
							<ul>
								<% role.each_ability_value do |a,has| %>
									<li>
										<%= hidden_field_tag "project[roles][#{role_prefix}][was_ability][#{a}]", has %>
										<label class="checkbox oneline">
											<%= check_box_tag "project[roles][#{role_prefix}][set_ability][#{a}]", true, has %>
											<%= Ability.stringify(a) %>
										</label>
									</li>
								<% end %>
							</ul>
						</div>
						<div style="display:inline-block;vertical-align:top;">
							Users:
							<ul>
								<% roleMembers = {} %>
								<% role.users.each do |u| %>
									<li>
										<% roleMembers[u.id] = true %>
										<%= hidden_field_tag "project[roles][#{role_prefix}][had_member][#{u.id}]", true %>
										<label class="checkbox">
											<%= check_box_tag "project[roles][#{role_prefix}][still_member][#{u.id}]", true, true %>
											<%= u.username %>
										</label>
									</li>
								<% end %>
								<% @project.users.each do |u| %>
									<% next if roleMembers[u.id] %>
									<li><label class="checkbox">
										<%= check_box_tag "project[roles][#{role_prefix}][new_member][#{u.id}]", true, false %>
										<%= u.username %>
									</label></li>
								<% end %>
								<li>
									<%= text_field_tag "project[roles][#{role_prefix}][new_members]", '', placeholder: 'New users' %>
								</li>
							</ul>
						</div>
					<% end -%>
				</li>
			<% end -%>
  </ul>


	<div class="actions">
		<%= f.submit :class => 'btn btn-primary' %>
		<%= link_to 'Delete project', project_path(@project), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
	</div>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing project <%= link_to @project.name, project_path(@project) %></h1>

<%= render 'form' %>

<%= link_to 'New Project role', project_role_new_path(@project) %>

app/views/projects/index.html.erb
<h1>Projects</h1>

<ul>
	<% @projects.each do |project| %>
		<li>
			<%= link_to project.name, project_path(project) %>
			<% if can? :manage, project -%>
		 		<a href="<%= edit_project_path(project) %>"><i class="icon-pencil" style="vertical-align: middle"></i></a>
		 		<a href="<%= project_path(project) %>" data-confirm="Are you sure?" data-method="delete" rel="nofollow"><i class="icon-trash" style="vertical-align: middle"></i></a>
		 	<% end -%>
		</li>
	<% end %>
</ul>

<h3>Create new project</h3>

<%= form_tag(projects_path, :class => "form-inline") do %>
	<%= text_field_tag "project[name]", '', :placeholder => "Name" %>
	<%= submit_tag "Create project", :class => 'btn btn-success' %>
<% end %>

app/views/projects/show.html.erb
<h1>
	Project <%= @project.name %>
	<% if can? :manage, @project %>
		<a href="<%= edit_project_path(@project) %>"><i class="icon-pencil" style="vertical-align: middle"></i></a>
	<% end %>
</h1>

<% @project.roles.each do |role| %>
  <div>
    <b><%= role.name %></b><br>

    <ul>
    <% role.users.each do |user| %>
      <li><%= user.email %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<h3>Lists</h3>

<ul>
	<% @project.lists.each do |list| %>
		<li>
			<%= link_to list.name, list %>
			<% if can? :manage_list, @project %>
		 		<a href="<%= edit_todo_list_path(list) %>"><i class="icon-pencil" style="vertical-align: middle"></i></a>
		 		<a href="<%= todo_list_path(list) %>" data-confirm="Are you sure?" data-method="delete" rel="nofollow"><i class="icon-trash" style="vertical-align: middle"></i></a>
		 	<% end %>
		</li>
	<% end %>
</ul>

<% if !can? :manage, @project or !@project.last_managing_user %>
<%= link_to 'Leave project', project_leave_path(@project), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
<br /><br />
<% end %>

<% if can? :manage_list, Project %>
  <%= form_tag(project_lists_path(@project), :class => "form-inline") do %>
    <%= text_field_tag "new_list[name]", '', :placeholder => "Name" %>
    <%= submit_tag "Create Todo List", :class => 'btn btn-success' %>
  <% end %>
<% end %>

<% if can? :create, @project
	@todo_item = TodoItem.new() -%>
	<h3>New Todo Item</h3>

	<%= render "todo_lists/new_item" %>
<% end -%>