config/routes.rb
Sudu::Application.routes.draw do
  devise_scope :user do
    get :new_user_session, :path => 'login', :to => "devise/sessions#new"
    post :user_session, :path => 'login', :to => "devise/sessions#create"
    match :destroy_user_session, :path => 'logout', :to => "devise/sessions#destroy", :via => [ :post, :delete ]

    get :new_user_registration, :path => 'sign_up', :to => "users/registrations#new"
    post :reset_feed_token, :path => 'users/reset_feed_token', :to => "users/registrations#reset_feed_token"
  end
  devise_for :users, :skip => :sessions, :controllers => { :registrations => 'users/registrations' } 

  resources :projects, :only => [:index,:show,:edit,:update,:create,:destroy] do
    delete :leave
    get :role_new, :path => 'roles/new', :action => :new_role
    delete :role_destroy, :path => "roles/:id", :action => :destroy_role
    
    post :lists, :action => :create_list
  end

  resources :todo_items, :path => :items, :only => [:show,:update,:destroy] do
    resources :todo_item_changes, :path => :changes, :only => [:show]
  end
  resources :todo_lists, :path => :lists, :only => [:show,:edit,:update,:destroy] do
    collection do
      post :create_item
    end
    get :item_new, :path => 'items/new', :action => :new_item
  end

  match :markdown, :controller => :markdown, :action => :index, :via => [ :get, :put, :post ]

  get :feed, :to => 'feed#index'

  devise_scope :admin do
    get :new_admin_session, :path => 'admin/login', :to => "devise/sessions#new"
    post :admin_session, :path => 'admin/login', :to => "devise/sessions#create"
    match :destroy_admin_session, :path => 'admin/logout', :to => "devise/sessions#destroy", :via => [ :post, :delete ]
  end
  devise_for :admins, :path => "admin/admins", :skip => :sessions

  namespace :admin do
    authenticated :admin do
      get :dashboard_index, :path => '/', :to => "dashboard#index"
    end

    resources :projects, :only => [:index,:create,:show,:update,:destroy] do
      get :role_new, :path => 'roles/new', :action => :new_role
      delete :role_destroy, :path => "roles/:id", :action => :destroy_role
    end
    resources :admins, :only => [:index,:create,:show,:update,:destroy]
    resources :users, :only => [:index,:create,:show,:update,:destroy] do
      member do
        post :become
        post :lock
        post :unlock
        post :restore
        post :confirm
        post :make_admin
      end
    end
  end

  authenticated :user do
    get :dashboard_index, :path => '/', :to => "dashboard#index"
  end

  devise_scope :user do
    root :to => "devise/sessions#new"
  end

  devise_scope :admin do
    get :admin_root, :path => 'admin', :to => "devise/sessions#new"
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable
  # :lockable, :timeoutable and :omniauthable
  # -- , :trackable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable,
         :authentication_keys => [:login],
         :reset_password_keys => [:login],
         :confirmation_keys => [:login]

  validates_format_of :username, :with => /\A[a-z0-9_\-]+\Z/
  validate :validate_deleted_no_projects

  has_and_belongs_to_many :todo_items
  has_and_belongs_to_many :project_roles
  has_many :projects, :through => :project_roles, :uniq => true
  has_many :todo_lists, :through => :projects, :source => :lists
  has_many :all_todo_items, :through => :projects, :source => :items
  has_many :changes, :class_name => "TodoItemChanges"
  has_many :all_changes, :class_name => "TodoItemChanges", :through => :all_todo_items, :source => :changes

  has_one :admin, :foreign_key => :email, :primary_key => :email

  # Setup accessible (or protected) attributes for your model
  attr_accessible :username, :email, :password, :password_confirmation, :remember_me, :deleted_at,
     :locked, :feed_authentication_token, :confirmed_at
  attr_readonly :username

  # virtual attribute for :username + :email
  attr_accessor :login

  after_initialize :ensure_feed_authentication_token

  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      login = login.downcase
      where(conditions).where(arel_table[:username].lower.eq(login).or(arel_table[:email].lower.eq(login))).first
    else
      where(conditions).first
    end
  end

  def self.search(login)
    login = "%#{login}%"
    where(arel_table[:username].lower.matches(login).or(arel_table[:email].lower.matches(login)))
  end

  def validate_deleted_no_projects
    if deleted_at and projects.count > 0
      errors[:base] << "Cannot delete account while it is member of projects"
    end
  end

  def active_for_authentication?
    super and !locked and deleted_at.nil?
  end

  def self.find_first_by_feed_token(key)
    where(:feed_authentication_token => key).first
  end

  def ensure_feed_authentication_token
    return self.feed_authentication_token unless self.feed_authentication_token.blank?
    self.feed_authentication_token = loop do
      token = Devise.friendly_token
      break token unless User.where(:feed_authentication_token => token).first
    end
  end

  def reset_feed_authentication_token
    self.feed_authentication_token = loop do
      token = Devise.friendly_token
      break token unless User.where(:feed_authentication_token => token).first
    end
  end

  def reset_feed_authentication_token!
    reset_feed_authentication_token
    save!
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::AdminController
  def index
    @users = User

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users.all }
    end
  end

  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  def create
    p = params[:user]
    @user = User.new(:username => p[:username], :email => p[:email], :password => p[:password])
    @user.skip_confirmation!
    @user.save

    respond_to do |format|
      if @user.valid? and @user.errors.empty? then
        format.html { redirect_to admin_users_url, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: admin_user_path(@user) }
      else
        format.html { render :action => "show" }
        format.json { render :json => { :errors => @user.errors }, :status => :unprocessable_entity}
      end
    end
  end

  def update
    p = params[:user]
    @user = User.find(params[:id])
    if @user.email != p[:email]
      @user.email = p[:email]
      @user.skip_reconfirmation!
    end
    if !p[:password].blank?
      @user.password = p[:password]
    end
    @user.save

    respond_to do |format|
      if @user.errors.empty? then
        format.html { redirect_to admin_users_url, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "show" }
        format.json { render :json => { :errors => @user.errors }, :status => :unprocessable_entity}
      end
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.transaction do
      @user.projects.each do |project|
        if project.users.uniq == [@user]
          project.destroy
        else
          project.roles.each do |role|
            role.users.delete(@user)
          end
        end
      end

      @user.deleted_at = Time.now
      @user.save(:validate => false) if @user.errors.empty?
      raise ActiveRecord::Rollback unless @user.errors.empty?
    end

    respond_to do |format|
      if @user.errors.empty? then
        format.html { redirect_to admin_user_url(@user), notice: "User #{@user.username} was successfully disabled." }
        format.json { head :no_content }
      else
        @user.reload
        format.html { render :action => "show" }
        format.json { render :json => { :errors => @user.errors }, :status => :unprocessable_entity}
      end
    end
  end

  def restore
    @user = User.find(params[:id])
    @user.deleted_at = nil
    @user.save

    respond_to do |format|
      if @user.errors.empty? then
        format.html { redirect_to admin_user_url(@user), notice: "User #{@user.username} was successfully restored." }
        format.json { head :no_content }
      else
        format.html { render :action => "show" }
        format.json { render :json => { :errors => @user.errors }, :status => :unprocessable_entity}
      end
    end
  end

  def lock
    @user = User.find(params[:id])
    @user.locked = true
    @user.save

    respond_to do |format|
      if @user.errors.empty? then
        format.html { redirect_to admin_user_url(@user), notice: "User #{@user.username} was successfully locked." }
        format.json { head :no_content }
      else
        format.html { render :action => "show" }
        format.json { render :json => { :errors => @user.errors }, :status => :unprocessable_entity}
      end
    end
  end

  def unlock
    @user = User.find(params[:id])
    @user.locked = false
    @user.save

    respond_to do |format|
      if @user.errors.empty? then
        format.html { redirect_to admin_user_url(@user), notice: "User #{@user.username} was successfully unlocked." }
        format.json { head :no_content }
      else
        format.html { render :action => "show" }
        format.json { render :json => { :errors => @user.errors }, :status => :unprocessable_entity}
      end
    end
  end

  def confirm
    @user = User.find(params[:id])
    @user.skip_confirmation!
    @user.save

    respond_to do |format|
      if @user.errors.empty? then
        format.html { redirect_to admin_user_url(@user), notice: "User #{@user.username} was successfully confirmed." }
        format.json { head :no_content }
      else
        format.html { render :action => "show" }
        format.json { render :json => { :errors => @user.errors }, :status => :unprocessable_entity}
      end
    end
  end

  def become
    @user = User.find(params[:id])
    active = @user.active_for_authentication?
    sign_in(:user, @user, :bypass => true) if active

    respond_to do |format|
      if active
        format.html { redirect_to root_url, notice: "Logged in as user #{@user.username}" }
        format.json { head :no_content }
      else
        flash[:alert] = "Cannot become inactive user"
        format.html { render :action => "show" }
        format.json {
          @user.errors[:base] << "Cannot become inactive user"
          render :json => { :errors => @user.errors }, :status => :unprocessable_entity
        }
      end
    end
  end

  def make_admin
    @user = User.find(params[:id])
    error = nil
    if @user.active_for_authentication?
      @admin = Admin.new(email: @user.email)
      @admin.encrypted_password = @user.encrypted_password
      @admin.save(:validate => false)
      if !@admin.valid?
        error = "Administrator already exists: " + @admin.errors.to_a.join(',')
      end
    else
      error = "Cannot copy inactive user to admins"
    end

    respond_to do |format|
      unless error
        format.html { redirect_to admin_admin_url(@admin), notice: "Administrator #{@admin.email} was successfully created from user." }
        format.json { head :no_content }
      else
        flash[:alert] = error
        format.html { render :action => "show" }
        format.json {
          @user.errors[:base] << error
          render :json => { :errors => @user.errors }, :status => :unprocessable_entity
        }
      end
    end
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  prepend_before_filter :authenticate_scope!, :only => [:edit, :update, :destroy, :reset_feed_token]

  ALLOWED_FIELDS = {
    :email => true,
    :password => true,
    :password_confirmation => true,
    :current_password => true,
  }

  def new
    raise CanCan::AccessDenied.new("Not authorized!") unless Sudu::Application.config.allow_registration
    super
  end

  def create
    raise CanCan::AccessDenied.new("Not authorized!") unless Sudu::Application.config.allow_registration
    resource_params.select! { |key,v| key.to_sym == :username || ALLOWED_FIELDS[key.to_sym] }
    super
  end

  def update
    resource_params.select! { |key,v| ALLOWED_FIELDS[key.to_sym] }
    super
  end

  def destroy
    resource.deleted_at = Time.now
    if resource.save
      set_flash_message :notice, :destroyed
      sign_out_and_redirect(self.resource)
    else
      respond_to do |format|
        resource.errors.clear
        set_flash_message :alert, :has_projects
        format.html { render action: "edit" }
        format.json { render status: :unprocessable_entity }
      end
    end
  end

  def reset_feed_token
    current_user.reset_feed_authentication_token
    respond_to do |format|
      if current_user.save
        format.html { redirect_to edit_user_registration_path, notice: 'Reset feed token successfully.' }
        format.json { head :no_content }
      else
        format.html { redirect_to edit_user_registration_path, alert: current_user.errors.to_a.join(', ') }
        format.json { render json: current_user.errors, status: :unprocessable_entity }
      end
    end
  end
end

app/views/admin/users/index.html.erb
<h1>Users</h1>

<form action="<%= admin_users_path %>" class="form-search">
	<div class="input-append">
		<input type="text" class="search-query" name="q" value="<%= params[:q] %>">
		<button type="submit" class="btn"><i class="icon-search"></i></button>
	</div>
</form>

<% @users = @users.search(params[:q]) unless params[:q].blank? -%>

<% @users = @users.page(params[:page]) -%>
<%= paginate @users %>

<table class="table table-striped table-hover table-condensed" style="width: auto;">
	<thead><tr><th class="span2">Username</th><th class="span4">Email</th><th>Status</th></tr></thead>
	<tbody>
		<% @users.each do |user| -%>
			<tr>
				<td><%= link_to user.username, admin_user_path(user) %></td>
				<td><%= link_to user.email, admin_user_path(user) %></td>
				<td><%= user.locked ? 'Locked' : user.deleted_at ? 'Deleted' : user.confirmed? ? 'Active' : 'Registered' %></td>
			</tr>
		<% end -%> 
	</tbody>
</table>

<h3>Create new user account</h3>

<%= form_tag(admin_users_path, :class => "form-inline") do %>
	<%= text_field_tag "user[username]", '', :placeholder => "Username", :autocomplete => "off" %>
	<%= text_field_tag "user[email]", '', :placeholder => "Email", :autocomplete => "off" %>
	<%= password_field_tag "user[password]", '', :placeholder => "Password", :autocomplete => "off" %>
	<%= submit_tag "Create account", :class => 'btn btn-success' %>
<% end %>

app/views/admin/users/show.html.erb
<h2>User <%= @user.username + ' <' + @user.email + '>' %></h2>

<div class="tabbable">
	<ul class="nav nav-tabs">
		<li class="active"><a data-target="#user-account" data-toggle="tab">Account</a></li>
		<li><a data-target="#user-projects" data-toggle="tab">Projects</a></li>
	</ul>
	
	<div class="tab-content">
		<div class="tab-pane active" id="user-account">


<%= form_for(@user, :url => @user.new_record? ? admin_users_path : admin_user_path(@user)) do |f| -%>
	<% if @user.errors.any? -%>
		<div id="error_explanation">
			<h2><%= pluralize(@user.errors.count, "error") %> prohibited this user account from being saved:</h2>

			<ul>
				<% @user.errors.full_messages.each do |msg| -%>
					<li><%= msg %></li>
				<% end -%>
			</ul>
		</div>
	<% end -%>

	<div class="form-horizontal">
		<div class="control-group">
			<label class="control-label">Status</label>
			<div class="controls">
				<input type="text" disabled value="<%= @user.locked ? 'Locked' : @user.deleted_at ? 'Deleted' : @user.confirmed? ? 'Active' : 'Registered' %>" />
				<br /><br />
<% if @user.locked -%>
				<a class="btn btn-info" href="<%= unlock_admin_user_path(@user) %>" data-method="post" rel="nofollow">Unlock</a>
<% elsif @user.deleted_at -%>
				<a class="btn btn-info" href="<%= restore_admin_user_path(@user) %>" data-method="post" rel="nofollow">Restore</a>
				<a class="btn btn-danger" href="<%= lock_admin_user_path(@user) %>" data-method="post" rel="nofollow">Lock</a>
<% elsif @user.confirmed? -%>
				<a class="btn btn-danger" href="<%= admin_user_path(@user) %>" data-confirm="Are you sure you want to delete this user? This will also delete all projects the user is the only member of." data-method="delete" rel="nofollow">Delete</a>
				<a class="btn btn-danger" href="<%= lock_admin_user_path(@user) %>" data-method="post" rel="nofollow">Lock</a>
<% else -%>
				<a class="btn btn-info" href="<%= confirm_admin_user_path(@user) %>" data-method="post" rel="nofollow">Confirm</a>
				<a class="btn btn-danger" href="<%= admin_user_path(@user) %>" data-confirm="Are you sure you want to delete this user? This will also delete all projects the user is the only member of." data-method="delete" rel="nofollow">Delete</a>
				<a class="btn btn-danger" href="<%= lock_admin_user_path(@user) %>" data-method="post" rel="nofollow">Lock</a>
<% end -%>
			</div>
		</div>
		<div class="control-group">
			<label class="control-label">Admin Account</label>
			<div class="controls">
<% if @user.admin -%>
				<div class="controls-text"><%= link_to @user.email, admin_admin_path(@user.admin) %></div>
<% else -%>
				<%= link_to 'Create Admin account', make_admin_admin_user_path(@user), :method => :post, :class => 'btn btn-warning' %>
				<br />With same email/password
<% end -%>
			</div>
		</div>
		<div class="control-group">
			<%= f.label :username, class: "control-label" %>
			<div class="controls"><%= f.text_field :username %></div>
		</div>

		<div class="control-group">
			<%= f.label :email, class: "control-label" %>
			<div class="controls"><%= f.email_field :email %></div>
		</div>

		<div class="control-group">
			<%= f.label :password, class: "control-label" %>
			<div class="controls">
				<%= f.password_field :password, :autocomplete => "off" %>
				<br /><i>(leave blank if you don't want to change it)</i>
			</div>
		</div>

		<div class="control-group"><div class="controls">
			<%= f.submit @user.new_record? ? "Create" : "Update", class: 'btn btn-primary' %>
		</div></div>

		<div class="control-group"><div class="controls">
			<%= link_to 'Become user', become_admin_user_path(@user), :method => :post, class: 'btn btn-warning' %>
		</div></div>
	</div>

<% end -%>


		</div>
		<div class="tab-pane" id="user-projects">
<ul>
	<% @user.projects.each do |project| %>
		<li>
			<%= link_to project.name, admin_project_path(project) %>
	 		<a href="<%= admin_project_path(project) %>" data-confirm="Are you sure?" data-method="delete" rel="nofollow"><i class="icon-trash" style="vertical-align: middle"></i></a>
		</li>
	<% end %>
</ul>
		</div>
	</div>
</div>